# write docker-compse.yml for frontend and backend
version: "3.9"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: ict4d-frontend:v1
        restart: always
        environment:
          - REACT_APP_API_BASE_URL=http://localhost:4000
        ports:
        - "3000:3000"
        depends_on:
        - backend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: ict4d-backend:v1
        ports:
        - "4000:4000"

